import type { LoanApplication } from '@/types/finance';

const DEMO_TENANT = '11111111-1111-1111-1111-111111111111';

/** Riwayat kredit lintas koperasi — selaras dengan output chaincode credit-history. */
const PADIWANGI = {
  tenantId: 'PadiwangiMSP',
  tenantName: 'Koperasi Padiwangi',
  totalLoans: 3,
  settledLoans: 2,
  activeArrears: 1,
  lastUpdated: '2026-06-12T17:24:20.000Z',
};

const MARGA_MULYA = {
  tenantId: 'MargaMulyaMSP',
  tenantName: 'Koperasi Marga Mulya',
  totalLoans: 2,
  settledLoans: 2,
  activeArrears: 0,
  lastUpdated: '2026-05-30T08:00:00.000Z',
};

/** Pengajuan contoh untuk mode pratinjau (sudut pandang pengurus). */
export const SAMPLE_APPLICATIONS: LoanApplication[] = [
  {
    id: 'demo-loan-01',
    applicantId: 'demo-anggota-1',
    applicantName: 'Sukarno Hadi',
    targetTenantId: DEMO_TENANT,
    amount: 28_000_000,
    purpose: 'Traktor mini untuk olah lahan 2 ha',
    status: 'pending',
    creditScore: 58,
    crossTenantData: [PADIWANGI],
    createdAt: '2026-06-12T02:00:00Z',
    financingType: 'asset',
    assetName: 'Traktor mini Quick G1000',
    assetCategory: 'Alat olah tanah',
    assetPrice: 32_000_000,
    vendorName: 'CV Tani Jaya Mesin',
    downPayment: 4_000_000,
    tenorMonths: 24,
    marginPct: 0,
  },
  {
    id: 'demo-loan-02',
    applicantId: 'demo-anggota-2',
    applicantName: 'Rina Marlina',
    targetTenantId: DEMO_TENANT,
    amount: 9_500_000,
    purpose: 'Pompa air irigasi sawah',
    status: 'approved',
    creditScore: 92,
    crossTenantData: [MARGA_MULYA],
    createdAt: '2026-06-10T04:00:00Z',
    financingType: 'asset',
    assetName: 'Pompa air Honda WB30',
    assetCategory: 'Pompa air',
    assetPrice: 9_500_000,
    vendorName: 'Toko Mesin Subur',
    downPayment: 0,
    tenorMonths: 12,
    marginPct: 0,
  },
  {
    id: 'demo-loan-03',
    applicantId: 'demo-anggota-3',
    applicantName: 'Bambang Wijaya',
    targetTenantId: DEMO_TENANT,
    amount: 15_000_000,
    purpose: 'Alat panen padi (power thresher)',
    status: 'active',
    creditScore: 84,
    crossTenantData: [MARGA_MULYA],
    createdAt: '2026-05-20T03:00:00Z',
    financingType: 'asset',
    assetName: 'Power thresher Saprotan ST-80',
    assetCategory: 'Alat panen',
    assetPrice: 15_000_000,
    vendorName: 'CV Agro Mandiri',
    downPayment: 0,
    tenorMonths: 18,
    marginPct: 0,
    disbursedAt: '2026-05-22T03:00:00Z',
  },
  {
    id: 'demo-loan-04',
    applicantId: 'demo-anggota-4',
    applicantName: 'Dewi Anggraini',
    targetTenantId: DEMO_TENANT,
    amount: 6_000_000,
    purpose: 'Sprayer elektrik & selang',
    status: 'settled',
    creditScore: 96,
    crossTenantData: [MARGA_MULYA],
    createdAt: '2026-01-15T03:00:00Z',
    financingType: 'asset',
    assetName: 'Sprayer elektrik 16L (5 unit)',
    assetCategory: 'Lainnya',
    assetPrice: 6_000_000,
    vendorName: 'Toko Tani Makmur',
    downPayment: 0,
    tenorMonths: 6,
    marginPct: 0,
    disbursedAt: '2026-01-16T03:00:00Z',
    settledAt: '2026-06-01T03:00:00Z',
    assetTransferredAt: '2026-06-01T03:00:00Z',
  },
];
