OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: PadiwangiMSP
    Domain: padiwangi.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: MelatiJayaMSP
    Domain: melatijaya.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: SumberMakmurMSP
    Domain: sumbermakmur.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: TirtaBersamaMSP
    Domain: tirtabersama.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: HarapanBaruMSP
    Domain: harapanbaru.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: DinasMSP
    Domain: dinas.arta.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1